import './globals.css';
import UpdateNotification from './UpdateNotification'; 

export const metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <UpdateNotification /> 
      </body>
    </html>
  );
}